port: 8080

logger-output-path:

oauthStateString: "kjfgkldfjglkjakljgkldajlkdfankjjakldgjkaldjgalkjglkadjglkadjk"

google:
  clientID: "812913212349-nv9rc3hgjerj134mapsksu1nq1m9b3nd.apps.googleusercontent.com"
  clientSecret: "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"